services:
  - type: web
    name: dd-tours
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DD_Tours.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DD_Tours.settings
      - key: PYTHON_VERSION
        value: 3.11
